<div class="row" id="header-isi">
    <div class="col-sm-12">
        <a href="<?php echo base_url();?>" title="kembali ke halaman utama"><span style="margin-right:10px;" class="fa fa-home"></span>halaman utama</a>
        <h1>Informasi Profil Sekolah</h1>
    </div>
</div>

<div class="row">
  <div class="col-sm-12">
      <div class="menu-pull-bar">Informasi Profil Sekolah SD</div>
            
      <ul class="nav nav-tabs">
        <li class="active nav-list green-light"><a href="#kriteria">SD</a></li>
        <li class="nav-list green-light"><a href="#syaratUmum2">SMP</a></li>
        <li class="nav-list green-light"><a href="#kriteria">SMA</a></li>
        <li class="nav-list green-light"><a href="#syaratUmum2">SMK</a></li>
      </ul>
      <br>
       <table class="table table-striped table-bordered" id="datatable">
          <thead>
              <tr>
                  <th>Kecamatan</th>
                  <th>Nama</th>
                  <th>Alamat</th>
                  <th>Telepon</th>
                  <th>Status</th>
                  <th>Akreditasi</th>
                  <th>Link Profil</th>
              </tr>
          </thead>
          <tbody>
              <tr><td>Kec. Asemrowo</td><td>SMA TANWIR SURABAYA</td><td>Jl. Sekolahan  No. 41 Surabaya        </td><td>031-5460686         </td><td>S</td><td>c</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532122" target="_blank">link</a></td></tr>
              <tr><td>Kec. Benowo</td><td>SMAN 12 SURABAYA</td><td>Jl .SEMEMI SURABAYA    </td><td> 031-7406368   </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532245" target="_blank">link</a></td></tr>
              <tr><td>Kec. Benowo</td><td>MAS AL FATICH</td><td>Jalan Tambak  Osowilangun No. 98 Surabaya     </td><td>0317483627 </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532005" target="_blank">link</a></td></tr>
              <tr><td>Kec. Benowo</td><td>SMA WACHID HASYIM 5 SURABAYA</td><td>Jl .Raya Sememi No.7 Surabaya           </td><td>031-7440937         </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532109" target="_blank">link</a></td></tr>
              <tr><td>Kec. Bubutan</td><td>SMA Kristen Pirngadi Surabaya</td><td>JL. PIRNGADI NO. 12-14                     </td><td>    031.5344562     </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20539237" target="_blank">link</a></td></tr>
              <tr><td>Kec. Bulak</td><td>SMAN 3 SURABAYA</td><td>Jl. MEMET S. KOMP. TNI-AL KENJERAN SURABAYA          </td><td> 3812356         </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532235" target="_blank">link</a></td></tr>
              <tr><td>Kec. Bulak</td><td>SMA TRI GUNA BHAKTI SURABAYA</td><td>Jl. KYAI TAMBAK DERES NO. 34 SURABAYA     </td><td> 03151503273    </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532126" target="_blank">link</a></td></tr>
              <tr><td>Kec. Dukuh Pakis</td><td>SMA KATOLIK KARITAS III SURABAYA</td><td>Jl. SIMPANG DARMO PERMAI UTARA VII/11 SURABAYA               </td><td> 7314795            </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532143" target="_blank">link</a></td></tr>
              <tr><td>Kec. Dukuh Pakis</td><td>SMA KRISTEN DHARMA MULYA SURABAYA</td><td>Jl. RAYA DUKUH KUPANG BARAT32 SURABAYA               </td><td> 031-5664164        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532132" target="_blank">link</a></td></tr>
              <tr><td>Kec. Dukuh Pakis</td><td>SMA KRISTEN PETRA 1 SURABAYA</td><td>Lingkar Dalam Barat Perum Graha Famili     </td><td>  (031) 7347916   </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532135" target="_blank">link</a></td></tr>
              <tr><td>Kec. Dukuh Pakis</td><td>SMA PAMARDI PUTRA</td><td>JL. Dukuh Pakis No 40     </td><td> 031-5612704    </td><td>S</td><td>C</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532158" target="_blank">link</a></td></tr>
              <tr><td>Kec. Gayungan</td><td>SMAN 15 SURABAYA</td><td>Jl. Menanggal Selatan 103 Surabaya                  </td><td> 031-8290473        </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532237" target="_blank">link</a></td></tr>
              <tr><td>Kec. Gayungan</td><td>MA Ittaqu</td><td>Jl. MENANGGAL IV 31 F  </td><td>       8275887 </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20541314" target="_blank">link</a></td></tr>
              <tr><td>Kec. Gayungan</td><td>SMA AL FALAH KETINTANG</td><td>JALAN KETINTANG MADYA 81          </td><td> 0318291502         </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20541315" target="_blank">link</a></td></tr>
              <tr><td>Kec. Gayungan</td><td>SMA INTENSIF TARUNA PEMBANGUNAN SURABAYA</td><td>Jl. DUKUH MENANGGAL XII/4 SURABAYA ( KOMPLEKS UNIPA )                 </td><td>8281182/03170541182 </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532388" target="_blank">link</a></td></tr>
              <tr><td>Kec. Gayungan</td><td>SMA KEMALA BHAYANGKARI 1 SURABAYA</td><td>Jl. AHMAD YANI 30-32 SURABAYA                 </td><td>031-8286995         </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532149" target="_blank">link</a></td></tr>
              <tr><td>Kec. Genteng</td><td>SMAN 1 SURABAYA</td><td>Jl. WIJAYA KUSUMA No. 48 SURABAYA               </td><td> 031-5345670        </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532242" target="_blank">link</a></td></tr>
              <tr><td>Kec. Genteng</td><td>SMAN 2 SURABAYA</td><td>Jl. WIJAYA KUSUMA No. 48 SURABAYA                        </td><td>0315345972          </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532230" target="_blank">link</a></td></tr>
              <tr><td>Kec. Genteng</td><td>SMAN 5 SURABAYA</td><td>Jl. KUSUMABANGSA 21 SURABAYA                         </td><td>+6231 5345155       </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532248" target="_blank">link</a></td></tr>
              <tr><td>Kec. Genteng</td><td>SMAN 6 SURABAYA</td><td>Jl. GUBERNUR SURYO No. 11 SURABAYA        </td><td> 0315345974       </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532260" target="_blank">link</a></td></tr>
              <tr><td>Kec. Genteng</td><td>SMAN 7 SURABAYA</td><td>Jl. NGAGLIK No. 27-29 SURABAYA          </td><td> 3718085         </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532261" target="_blank">link</a></td></tr>
              <tr><td>Kec. Genteng</td><td>SMAN 9 SURABAYA</td><td>Jl. WIJAYA KUSUMA NO.48 SURABAYA                             </td><td> 031-5342608        </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532263" target="_blank">link</a></td></tr>
              <tr><td>Kec. Genteng</td><td>SMA ATMA WIDYA SURABAYA</td><td>Jl. KAPASARI  No.3 - 5 SURABAYA     </td><td>031-3710469   </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532382" target="_blank">link</a></td></tr>
              <tr><td>Kec. Genteng</td><td>SMA PETRA 3 SURABAYA</td><td>Jl. KALI ANYAR 43  SURABAYA           </td><td>(031)5344210        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532172" target="_blank">link</a></td></tr>
              <tr><td>Kec. Genteng</td><td>SMAS IMKA SURABAYA</td><td>Jl. KOMBES POL. M. DURYAT 9  SURABAYA  </td><td>  </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532396" target="_blank">link</a></td></tr>
              <tr><td>Kec. Genteng</td><td>SMA TRIMURTI SURABAYA</td><td>Jl. GUBERNUR SURYO No.3  SURABAYA        </td><td>0315315608    </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532118" target="_blank">link</a></td></tr>
              <tr><td>Kec. Genteng</td><td>SMA TRISILA SURABAYA</td><td>JL. UNDAAN KULON 57-59 SBY                  </td><td> 031.5344364        </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532117" target="_blank">link</a></td></tr>
              <tr><td>Kec. Gubeng</td><td>SMA DAPENA 1 SURABAYA</td><td>Jl. SUMATERA 112 - 114  SURABAYA               </td><td> 5031453            </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532370" target="_blank">link</a></td></tr>
              <tr><td>Kec. Gubeng</td><td>SMA GALUH HANDAYANI </td><td>Jl. Manyar Sambongan 87-89  Surabaya       </td><td>  0315018129        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532399" target="_blank">link</a></td></tr>
              <tr><td>Kec. Gubeng</td><td>SMA GIKI 2 SURABAYA</td><td>Jl. RAYA GUBENG 45  SURABAYA                    </td><td>  031 5031053       </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532403" target="_blank">link</a></td></tr>
              <tr><td>Kec. Gubeng</td><td>SMA IT AL USWAH</td><td>Jln. Ngagel Tama Utara IV No. 2 - 8    </td><td>72542345   </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=69786332" target="_blank">link</a></td></tr>
              <tr><td>Kec. Gubeng</td><td>SMA KERTAJAYA SURABAYA</td><td>Jl. JUWINGAN I-B  SURABAYA             </td><td>5028917        </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532142" target="_blank">link</a></td></tr>
              <tr><td>Kec. Gubeng</td><td>SMA MAHARDHIKA SURABAYA</td><td>Jl. BARATA JAYA XII / 1  SURABAYA              </td><td> 5054448            </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532168" target="_blank">link</a></td></tr>
              <tr><td>Kec. Gubeng</td><td>SMA MARYAM SURABAYA</td><td>Jl. MANYAR SAMBONGAN 119  SURABAYA     </td><td> 0315017539    </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532170" target="_blank">link</a></td></tr>
              <tr><td>Kec. Gubeng</td><td>SMA MUHAMMADIYAH 2 SURABAYA</td><td>Jl. Pucang Anom 91 Surabaya      </td><td> 031-5021316        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532163" target="_blank">link</a></td></tr>
              <tr><td>Kec. Gubeng</td><td>SMA PRACTICA SURABAYA</td><td>Jl. KALIDAMI NO.14-16 SURABAYA      </td><td>   031-5053630   </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532096" target="_blank">link</a></td></tr>
              <tr><td>Kec. Gubeng</td><td>SMA YPPI - I SURABAYA</td><td>Jl. DHARMAHUSADA INDAH BARAT VI/1  SURABAYA             </td><td> 031-5936894        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532129" target="_blank">link</a></td></tr>
              <tr><td>Kec. Jambangan</td><td>SMAN 18 SURABAYA</td><td>Jl. BIBIS KARAH SAWAH No. 9 SURABAYA                   </td><td> 0318286003         </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532218" target="_blank">link</a></td></tr>
              <tr><td>Kec. Jambangan</td><td>SMA AL HIKMAH SURABAYA</td><td>JL. KEBONSARI  ELVEKA V  </td><td>8289097 </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20549721" target="_blank">link</a></td></tr>
              <tr><td>Kec. Jambangan</td><td>SMA KARTIKA WIJAYA SURABAYA</td><td>Jl. KARAH 182 SURABAYA        </td><td> 031-8283802      </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532395" target="_blank">link</a></td></tr>
              <tr><td>Kec. Jambangan</td><td>SMA SELALU MAJU</td><td> SIMOKWIJENAN</td><td> </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20132014" target="_blank">link</a></td></tr>
              <tr><td>Kec. Karangpilang</td><td>SMA KATOLIK SANTO YUSUP SURABAYA</td><td>Jl. KEBRAON I/6 BARAT  SURABAYA       </td><td>  7661552     </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532144" target="_blank">link</a></td></tr>
              <tr><td>Kec. Karangpilang</td><td>SMA KUSUMANAGARA SURABAYA</td><td>Jl.  Raya Mastrip No. 45 A SURABAYA     </td><td> 0317660695    </td><td>S</td><td>C</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532164" target="_blank">link</a></td></tr>
              <tr><td>Kec. Karangpilang</td><td>SMA MUHAMMADIYAH 4 SURABAYA</td><td>Jl. KEMLATEN BARU 43  SURABAYA      </td><td> 031-7664220     </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532161" target="_blank">link</a></td></tr>
              <tr><td>Kec. Kenjeran</td><td>SMAN 19 SURABAYA</td><td>Jl. KEDUNG COWEK 390 SURABAYA           </td><td> 51504844          </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532219" target="_blank">link</a></td></tr>
              <tr><td>Kec. Kenjeran</td><td>SMA TERBUKA 19</td><td> Jl Kedung Cowek No 390 Surabaya  </td><td> 51504844  </td><td>N</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=69727899" target="_blank">link</a></td></tr>
              <tr><td>Kec. Kenjeran</td><td>SMA WACHID HASYIM 1 SURABAYA</td><td>Jl. SIDOTOPO WETAN BARU NO.37  SURABAYA      </td><td> 0313764756     </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532108" target="_blank">link</a></td></tr>
              <tr><td>Kec. Krembangan</td><td>SMA HANG TUAH 1 SURABAYA</td><td>Jl. IKAN LUMBA-LUMBA 27  SURABAYA           </td><td>0313537810   </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532406" target="_blank">link</a></td></tr>
              <tr><td>Kec. Krembangan</td><td>SMA ISLAM KARTIKA SURABAYA</td><td>Jl. Kalianak Timur Gg. Lebar No. 7-11 Surabaya      </td><td> 0317480408     </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532391" target="_blank">link</a></td></tr>
              <tr><td>Kec. Krembangan</td><td>SMA KATOLIK FRATERAN SURABAYA</td><td>Jl. KEPANJEN 8  SURABAYA               </td><td>031 3524901         </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532131" target="_blank">link</a></td></tr>
              <tr><td>Kec. Krembangan</td><td>SMA KATOLIK STELLA MARIS SURABAYA</td><td>Jl. INDRAPURA 32 SURABAYA            </td><td> 031-3522174        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532146" target="_blank">link</a></td></tr>
              <tr><td>Kec. Krembangan</td><td>SMA KAWUNG 1 SURABAYA</td><td>Jl. PARANG KLITIK NO. 2  SURABAYA            </td><td> 0313531083         </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532147" target="_blank">link</a></td></tr>
              <tr><td>Kec. Krembangan</td><td>SMA KEMALA BHAYANGKARI 2 SURABAYA</td><td>Jl. GRESIK 39 SURABAYA           </td><td> 3559951          </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532150" target="_blank">link</a></td></tr>
              <tr><td>Kec. Krembangan</td><td>SMA TA`MIRIYAH SURABAYA</td><td>Jl. Indrapura 2  Surabaya            </td><td>031-3525931         </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532125" target="_blank">link</a></td></tr>
              <tr><td>Kec. Lakarsantri</td><td>SMAN 13 SURABAYA</td><td>Jl. LIDAH KULON SURABAYA         </td><td>7531770        </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532246" target="_blank">link</a></td></tr>
              <tr><td>Kec. Lakarsantri</td><td>SMA CIPUTRA</td><td> PURI WIDYA KENCANA SURABAYA          </td><td> 031-7415018        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20549499" target="_blank">link</a></td></tr>
              <tr><td>Kec. Lakarsantri</td><td>SMA CITA HATI WEST CAMPUS</td><td> Jl. Bukit Bali B-3 No. 6 Citraland     </td><td> 7404959     </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=60725637" target="_blank">link</a></td></tr>
              <tr><td>Kec. Lakarsantri</td><td>SMA MIMI SURABAYA</td><td>Jl. Bukit Telaga Golf TO 2/1-2 Surabaya      </td><td>0317415337         </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20566343" target="_blank">link</a></td></tr>
              <tr><td>Kec. Lakarsantri</td><td>SMA NUR HIDAYAH SURABAYA</td><td>Jl. JERUK NO. I  LAKARSANTRI  SURABAYA   </td><td> 031- 7525741  </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532157" target="_blank">link</a></td></tr>
              <tr><td>Kec. Lakarsantri</td><td>SMA PGRI 23 SURABAYA</td><td>Jl. JERUK NO. 188 SURABAYA </td><td> 81747576-71171961 </td><td>S</td><td>C</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532102" target="_blank">link</a></td></tr>
              <tr><td>Kec. Mulyorejo</td><td>SMA HIDAYATUL UMMAH SURABAYA</td><td>JL. MULYOREJO NO. 92 SURABAYA                  </td><td> 0315926675         </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20539254" target="_blank">link</a></td></tr>
              <tr><td>Kec. Mulyorejo</td><td>SMA IPIEMS SURABAYA</td><td>Jl. RAYA MENUR No. 125  SURABAYA       </td><td> 0315993014      </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532389" target="_blank">link</a></td></tr>
              <tr><td>Kec. Mulyorejo</td><td>SMA KRISTEN CITA HATI SURABAYA</td><td>Jl. Kejawan Putih Barat 28-30 Pakuwon City, Surabaya    </td><td> 0315915773   </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532140" target="_blank">link</a></td></tr>
              <tr><td>Kec. Mulyorejo</td><td>SMA KRISTEN GLORIA 2 SURABAYA</td><td>JL. KALISARI SELATAN I No. 3 PAKUWON CITY SURABAYA     </td><td> 031-5910077    </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20570825" target="_blank">link</a></td></tr>
              <tr><td>Kec. Mulyorejo</td><td>SMA KRISTEN PETRA 2 SURABAYA</td><td>Jl. MANYAR TIRTOASRI RAYA 1-3  SURABAYA       </td><td> 5926831      </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532136" target="_blank">link</a></td></tr>
              <tr><td>Kec. Mulyorejo</td><td>SMA LUQMAN AL- HAKIM SURABAYA</td><td>Jl. KEJAWAN PUTIH TAMBAK VI/1 SURABAYA    </td><td>031-5932325   </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532167" target="_blank">link</a></td></tr>
              <tr><td>Kec. Mulyorejo</td><td>SMA MUHAMMADIYAH 7 SURABAYA</td><td>Jl. SUTOREJO 98-100  SURABAYA          </td><td> 5996249         </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532154" target="_blank">link</a></td></tr>
              <tr><td>Kec. Pabean Cantian</td><td>SMA BARUNAWATI SURABAYA</td><td>Jl .PERAK BARAT 173 SURABAYA                  </td><td> 0313295548         </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532377" target="_blank">link</a></td></tr>
              <tr><td>Kec. Pabean Cantian</td><td>SMA MUJAHIDIN SURABAYA</td><td>Jl. TANJUNG PERAK BARAT 275 SURABAYA        </td><td> 3294516       </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532156" target="_blank">link</a></td></tr>
              <tr><td>Kec. Pabean Cantian</td><td>SMA SASANA BHAKTI </td><td>Jl. JAGALAN 132-136 SURABAYA           </td><td> 0313555891         </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532092" target="_blank">link</a></td></tr>
              <tr><td>Kec. Pakal</td><td>MAS IMAM SYAFI`I</td><td>JL. DK. BABAT RT.4 RW.1  NO. 111     </td><td>0317417676      </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20531997" target="_blank">link</a></td></tr>
              <tr><td>Kec. Pakal</td><td>SMA AL-AZHAR SURABAYA</td><td>Jl. PESAREHAN BEJI No.1 SURABAYA          </td><td>0317410171         </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532378" target="_blank">link</a></td></tr>
              <tr><td>Kec. Pakal</td><td>SMA CITRA BERKAT</td><td> Jl. RAYA BUKIT PALMA NO. 2. KAWASAN CITRALAND SBY   </td><td> 7412201 ext 16 </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=69787073" target="_blank">link</a></td></tr>
              <tr><td>Kec. Pakal</td><td>SMA WIJAYA PUTRA SURABAYA</td><td>Jl. RAYA BENOWO No. 1 - 3 SURABAYA     </td><td> 0317413061    </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532113" target="_blank">link</a></td></tr>
              <tr><td>Kec. Rungkut</td><td>SMAN 14 SURABAYA</td><td>Jl. RAYA TENGGILIS MEJOYO SURABAYA              </td><td>031 8414451         </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532238" target="_blank">link</a></td></tr>
              <tr><td>Kec. Rungkut</td><td>SMAN 17 SURABAYA</td><td>Jl. Rungkut Asri Tengah Komp Ykp Surabaya.                         </td><td>(031) 8700717       </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532217" target="_blank">link</a></td></tr>
              <tr><td>Kec. Rungkut</td><td>MA NURUL KHOIR</td><td>WONOREJO GG.MASJID NO. 2 RUNGKUT SURABAYA        </td><td>031-8706054    </td><td>S</td><td>T</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20577207" target="_blank">link</a></td></tr>
              <tr><td>Kec. Rungkut</td><td>SMA ISLAM JIWA NALA SURABAYA</td><td>Jl. RAYA KEDUNG ASEM 47-49 SURABAYA         </td><td>8791809        </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532390" target="_blank">link</a></td></tr>
              <tr><td>Kec. Rungkut</td><td>SMA Kr. INTAN PERMATA HATI</td><td>JL. RAYA KEDUNG BARUK NO. 112-114     </td><td> 0318794040    </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20573205" target="_blank">link</a></td></tr>
              <tr><td>Kec. Rungkut</td><td>SMA TARUNA SURABAYA</td><td>Jl. KALIRUNGKUT MEJOYO I/2 SURABAYA    </td><td>8411876 </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532124" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sambikerep</td><td>MAS AR ROSYID</td><td>Jl. Raya Lontar  No. 129    Surabaya    </td><td>(031) 7523478      </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532004" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sambikerep</td><td>SMA GARUDA SURABAYA</td><td>Jl .Raya Kuwukan No. 2 Surabaya                </td><td> 0317406252         </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532400" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sambikerep</td><td>SMA KRISTEN. MASA DEPAN CERAH</td><td>JL. DIAMOND HILL DH 1/11 CITRALAND SURABAYA     </td><td> 0317414838    </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20573071" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sambikerep</td><td>SMA MARGIE</td><td>Jl. Kuwukan No. 24 A Graha Natura Surabaya   </td><td>031-7440026  </td><td>S</td><td>-</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20561783" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sambikerep</td><td>SMA SHAFTA SURABAYA</td><td>Jl .RAYA LONTAR CITRA 177 B SURABAYA              </td><td> 031 7523504        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532107" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sambikerep</td><td>SMA SURABAYA TAIPEI SCHOOL</td><td>JL. DIAMOND HILL DR 1 NO. 15 CITRA RAYA SURABAYA</td><td>  </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20577828" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sambikerep</td><td>SMA TAMANSISWA SURABAYA</td><td>JL. LEMPUNG MULYA NO. 1A     </td><td> 0317405971   </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20539241" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sawahan</td><td>SMAN 21 SURABAYA</td><td>Jl. ARGOPURO 11-15 SURABAYA               </td><td>031-5350753         </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532232" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sawahan</td><td>SMA ADVENT SURABAYA</td><td>Jl. Anjasmoro 12 Surabaya      </td><td>031-5462984         </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532408" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sawahan</td><td>SMA ANTARTIKA SURABAYA</td><td>Jl. BANYU URIP KIDUL II/37 SURABAYA                    </td><td> 5664421            </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532381" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sawahan</td><td>SMA GEMA 45 SURABAYA</td><td>Jl. MAYJEN SUNGKONO 106 SURABAYA                </td><td> 5621570            </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532401" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sawahan</td><td>SMA GIKI 1 SURABAYA</td><td>Jl. DUKUH KUPANG UTARA I - 2 SURABAYA                    </td><td> 5634291            </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532402" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sawahan</td><td>SMA KATOLIK ST. LOUIS 2 SURABAYA</td><td>Jl. TIDAR 119 SURABAYA      </td><td> (031) 5310256     </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532151" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sawahan</td><td>SMA KAWUNG 2 SURABAYA</td><td>Jl. RAYA SIMO GUNUNG 25 SURABAYA      </td><td> 5613679     </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532148" target="_blank">link</a></td></tr>
              <tr><td>Kec. Semampir</td><td>SMAN 8 SURABAYA</td><td>Jalan Sultan Iskandar Muda No. 42 Surabaya                           </td><td>0313291732          </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532262" target="_blank">link</a></td></tr>
              <tr><td>Kec. Semampir</td><td>MAS IBNU HUSAIN</td><td>Jl. Pragoto no. 39-43 Surabaya</td><td>    0313760104     </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=90000039" target="_blank">link</a></td></tr>
              <tr><td>Kec. Semampir</td><td>MAS SUNAN AMPEL</td><td>Tenggumung Wetan Merpati II/I Surabaya </td><td> 0313769005 </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20531995" target="_blank">link</a></td></tr>
              <tr><td>Kec. Semampir</td><td>SMA AL - IRSYAD SURABAYA</td><td>Jl. SULTAN ISKANDAR MUDA 46 SURABAYA       </td><td>3293782      </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532366" target="_blank">link</a></td></tr>
              <tr><td>Kec. Semampir</td><td>SMA ATTARBIYAH SURABAYA</td><td>Jl. RAYA HANGTUAH NO 7 SURABAYA        </td><td>0888 014 83397  </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532384" target="_blank">link</a></td></tr>
              <tr><td>Kec. Semampir</td><td>SMA ISLAM LIL WATHON SURABAYA</td><td>Jl.WONOKUSUMO TENGAH 53-A SURABAYA            </td><td>  031-3724317       </td><td>S</td><td>C</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532392" target="_blank">link</a></td></tr>
              <tr><td>Kec. Simokerto</td><td>MA HASANUDDIN</td><td>Jl. Simolawang Baru I No.95 Surabaya            </td><td> 031-3722190        </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20539233" target="_blank">link</a></td></tr>
              <tr><td>Kec. Simokerto</td><td>MAS DARUSSALAM</td><td>Tambak Madu II/59-63       </td><td> 3732822       </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532001" target="_blank">link</a></td></tr>
              <tr><td>Kec. Simokerto</td><td>SMA MUHAMMADIYAH 1 SURABAYA</td><td>Jl. KAPASAN 73 - 75 SURABAYA         </td><td> 0313712425        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532171" target="_blank">link</a></td></tr>
              <tr><td>Kec. Simokerto</td><td>SMA TERPADU YPP NURUL HUDA</td><td>JL. SENCAKI NO. 64         </td><td> 031 78475651</td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20539242" target="_blank">link</a></td></tr>
              <tr><td>Kec. Simokerto</td><td>SMA YP 17 SURABAYA</td><td>Jl. SIDOTOPO WETAN 122 SURABAYA     </td><td>  031 3718063   </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532115" target="_blank">link</a></td></tr>
              <tr><td>Kec. Simokerto</td><td>SMA YPPI - II SURABAYA</td><td>Jl. KAPASARI 126 - 128 SURABAYA                       </td><td> 0313768968         </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532216" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sukolilo</td><td>SMAN 20 SURABAYA</td><td>JL.MEDOKAN SEMAMPIR      </td><td>0315935720     </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532231" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sukolilo</td><td>SMA 17 AGUSTUS 1945 SURABAYA</td><td>Jl. SEMOLOWARU NO. 45 SURABAYA      </td><td>5924165    </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532451" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sukolilo</td><td>SMA ANAK BANGSA</td><td>MANYAR KARTIKA TIMUR NO.6    </td><td>0315949619   </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=90000043" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sukolilo</td><td>SMA DR. SOETOMO SURABAYA</td><td>Jl. SEMOLOWARU NO 9 SURABAYA    </td><td> 5991783   </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532387" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sukolilo</td><td>SMA GIKI 3 SURABAYA</td><td>Jl. KLAMPIS JAYA NO. 11 SURABAYA    </td><td>031-5996405   </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532404" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sukolilo</td><td>SMA PANGLIMA SUDIRMAN SURABAYA</td><td>JL. NGINDEN II/135     </td><td>  5947528   </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20539239" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sukolilo</td><td>SMA SANTO HENDRIKUS SURABAYA</td><td>Jl. ARIEF RACHMAN HAKIM 40-44 SURABAYA     </td><td> 031-5941505    </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532089" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sukolilo</td><td>SMA SEKOLAH ALAM INSAN MULIA</td><td> JL. MEDOKAN SEMAMPIR INDAH 99-101 SURABAYA    </td><td> 031-5920033    </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=69756322" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sukolilo</td><td>SMA VITA</td><td>Jl. Arief Rahman Hakim 189-191       </td><td>031 5922690       </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20577229" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sukolilo</td><td>SMA YAPITA SURABAYA</td><td>JL. ARIEF RACHMAN HAKIM NO. 19        </td><td> 0315995242  </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20539244" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sukomanunggal</td><td>SMA ELYON</td><td> Jl. Raya Sukomanunggal Jaya no 33  </td><td>   031-7345463</td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=8000001" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sukomanunggal</td><td>SMA KR IPH 2</td><td> raya darmo permai III plasa segi 8 blok d-869A surabaya   </td><td> 0317340316   </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=90000045" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sukomanunggal</td><td>SMA KRISTEN GLORIA 1, SURABAYA</td><td>Jl. RAYA SUKOMANUNGGAL JAYA No.25-A SURABAYA   </td><td>703402  </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532133" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sukomanunggal</td><td>SMA KRISTEN KALAM KUDUS SURABAYA</td><td>Jl. RAYA KUPANG JAYA No.135 -136 SURABAYA              </td><td> 031 - 7312342      </td><td>S</td><td> A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532134" target="_blank">link</a></td></tr>
              <tr><td>Kec. Sukomanunggal</td><td>SMA SEJAHTERA  SURABAYA</td><td>Jl. Simomulyo I/3 Surabaya                            </td><td> 031-5313213        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532094" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tambaksari</td><td>SMAN 4 SURABAYA</td><td>Jl. Prof.Dr.Moestopo No.4 Surabaya                   </td><td> 031-5015455        </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532247" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tambaksari</td><td>MAS TAHSINUL AKHLAQ BAHRUL ULUM</td><td>Rangkah Masjid Gg. Buntu I/8-9A    </td><td> 3727002   </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20531994" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tambaksari</td><td>SMA GRACIA </td><td>Jl. GUBENG POJOK 15 SURABAYA       </td><td> 0315450051      </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532405" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tambaksari</td><td>SMA JAYA SAKTI SURABAYA</td><td>Jl. KARANG ASEM 43 SURABAYA   </td><td> 0315039455  </td><td>S</td><td>C</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532393" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tambaksari</td><td>SMA KATOLIK SANTA AGNES SURABAYA</td><td>Jl. MENDUT 7 SURABAYA      </td><td> 031-5026540     </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532138" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tambaksari</td><td>SMA KATOLIK SANTO STANISLAUS SURABAYA</td><td>Jl. KALIJUDAN 25-33 SURABAYA       </td><td> 3892472      </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532139" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tambaksari</td><td>SMA KRISTEN YBPK 1 SURABAYA</td><td>Jl. LUNTAS 33 SURABAYA      </td><td>031-5025748     </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532152" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tambaksari</td><td>SMA MARDI SIWI SURABAYA</td><td>Jl. TAMBAKSARI I/10 SURABAYA         </td><td>031 5033947       </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532169" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tambaksari</td><td>SMA PGRI 3 SURABAYA</td><td>Jl. KARANG EMPAT BESAR 133 SURABAYA       </td><td>031-3810960      </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532104" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tambaksari</td><td>SMA TRI TUNGGAL 1 SURABAYA</td><td>Jl .RANGKAH VI/55-57 SURABAYA             </td><td> (031) 3721455      </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532128" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tandes</td><td>SMAN 11 SURABAYA</td><td>Jl. PERUMNAS TANDES I SURABAYA                         </td><td>  031.7405420       </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532244" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tandes</td><td>MAS HASYIM ASY&apos</td><td></td><td>Balongsari Tama 3B/22         </td><td>         </td><td>S</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20531998" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tandes</td><td>MA SHOBRUL MAARIF</td><td>Banjarsugihan 1/6-8 Tandes Surabaya </td><td>  </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20577550" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tandes</td><td>SMA SARIPRAJA SURABAYA</td><td>Jl. BALONGSARI PRAJA V/1 SURABAYA  </td><td> 031-7406697 </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532091" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tandes</td><td>SMA TRI KARYA SURABAYA</td><td>Jl. LEMPUNG PERDANA 2 SURABAYA       </td><td> 0317419719      </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532127" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tegalsari</td><td>SMA KATOLIK ST. LOUIS 1 SURABAYA</td><td>Jl. POLISI ISTIMEWA NO. 7 SURABAYA                       </td><td>5681758             </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532145" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tegalsari</td><td>SMA SANTA MARIA SURABAYA</td><td>Raya Darmo 49, Surabaya      </td><td>566 1996     </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532087" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tenggilis Mejoyo</td><td>SMAN 16 SURABAYA</td><td>Jl. RAYA PRAPEN SURABAYA              </td><td> 031-8415492        </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532236" target="_blank">link</a></td></tr>
              <tr><td>Kec. Tenggilis Mejoyo</td><td>SMA DHARMA WANITA SURABAYA</td><td>Jl. KENDANGSARI V SURABAYA      </td><td>   0318418465   </td><td>S</td><td> A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532373" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wiyung</td><td>SMAN 22 SURABAYA</td><td>Jl. BALASKUMPRIK No.22 SURABAYA                </td><td>7664530             </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532233" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wiyung</td><td>MA AL-FATAH</td><td> </td><td> 031-78359345</td><td>S</td><td>C</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20576106" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wiyung</td><td>SMA MUHAMMADIYAH 9</td><td>Jl. Gogor IV No. 11-12          </td><td> 7663009         </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=69786333" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonocolo</td><td>MAN SURABAYA</td><td>Jl. Bendul Merisi Selatan IX/ No. 20 Surabaya            </td><td> 031-8435266        </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532023" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonocolo</td><td>SMAN 10 SURABAYA</td><td>Jl. JEMURSARI I/28 SURABAYA            </td><td> 031 8415273        </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532243" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonocolo</td><td>M AS Unggulan Amanatul Ummah Surabaya</td><td>JL. SIWALAN KERTO UTARA NO. 56, 63            </td><td> (031)8438754       </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20539232" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonocolo</td><td>SMA AN- NAJIYAH SURABAYA</td><td>Jl. SIDOSERMO IV/7 SURABAYA   </td><td> 8432974  </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532380" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonocolo</td><td>SMA BINA BANGSA SURABAYA</td><td>Jl. SIWALANKERTO UTARA II/7 SURABAYA            </td><td> 031-8493545        </td><td>S</td><td>C</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532376" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonocolo</td><td>SMA KRISTEN PETRA 5 SURABAYA</td><td>Jl. JEMUR ANDAYANI XVII/2 SURABAYA              </td><td> 8436474            </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532137" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonocolo</td><td>SMA SANTO CAROLUS SURABAYA</td><td>Jl. JEMUR ANDAYANI XXI/7 SURABAYA             </td><td>8491287           </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532088" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonocolo</td><td>SMA SURYO NUGROHO SURABAYA</td><td>Jl. BENDUL MERISI 156 SURABAYA SURABAYA       </td><td> 031-8414590      </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532120" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonocolo</td><td>SMA UNGGULAN AMANATUL UMMAH</td><td>Jl. Siwalankerto Utara 56, Wonocolo, Surabaya   </td><td>031 8476071   </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20577071" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonokromo</td><td>MAS ATTAUHID</td><td>Jl. Sidoresmo Dalam No. 37 Surabaya</td><td> 031-8412089</td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532003" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonokromo</td><td>SMA BINA TARUNA SURABAYA</td><td>Jl. GADUNG NO.17 - 19 SURABAYA            </td><td> 031-8495331        </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532375" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonokromo</td><td>SMA BUDI SEJATI SURABAYA</td><td>Jl. JAGIR WONOKROMO 112.SURABAYA             </td><td> 031-8411846        </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532368" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonokromo</td><td>SMA HANG TUAH 4 SURABAYA</td><td>Jl. BOGOWONTO NO.18.SURABAYA                  </td><td>5617695             </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532398" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonokromo</td><td>SMA KARTIKA IV-3</td><td>Jl. BRAWIJAYA No.38.SURABAYA      </td><td> 031-5681093     </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532394" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonokromo</td><td>SMA KHADIJAH SURABAYA</td><td>Jl. AHMAD YANI 2 - 4  SURABAYA     </td><td> 031 8284261    </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532141" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonokromo</td><td>SMA MUHAMMADIYAH 3 SURABAYA</td><td>Jl. GADUNG III/7  SURABAYA                  </td><td> 8415280            </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532162" target="_blank">link</a></td></tr>
              <tr><td>Kec. Wonokromo</td><td>SMA WIDYA DARMA SURABAYA</td><td>Jl. KETINGTANG 147  SURABAYA                  </td><td>031 8287401         </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532112" target="_blank">link</a></td></tr>

          </tbody>
      </table>
  </div>
</div>


       


