<div class="row" id="header-isi">
    <div class="col-sm-12">
        <a href="<?php echo base_url();?>" title="kembali ke halaman utama"><span style="margin-right:10px;" class="fa fa-home"></span>halaman utama</a>
        <h1>Informasi Profil Sekolah</h1>
    </div>
</div>

<div class="row">
  <div class="col-sm-12">
      <div class="menu-pull-bar">Informasi Profil Sekolah SMK</div>
            
      <ul class="nav nav-tabs">
        <li class="nav-list green-light"><a href="<?php echo site_url('umum/data_sekolah/sd');?>">SD</a></li>
        <li class="nav-list green-light"><a href="<?php echo site_url('umum/data_sekolah/smp');?>">SMP</a></li>
        <li class="nav-list green-light"><a href="<?php echo site_url('umum/data_sekolah/sma');?>">SMA</a></li>
        <li class="active nav-list green-light"><a href="#">SMK</a></li>
      </ul>
      <br>
       <table class="table table-striped table-bordered" id="datatable">
          <thead>
              <tr>
                  <th>Kecamatan</th>
                  <th>Nama</th>
                  <th>Alamat</th>
                  <th>Telepon</th>
                  <th>Status</th>
                  <th>Akreditasi</th>
                  <th>Link Profil</th>
              </tr>
          </thead>
          <tbody>
              <tr><td>Asemrowo</td><td>SMK TARUNA SURABAYA</td><td>Jl. ASEM RAYA  No. 27 SURABAYA     </td><td> 5455442    </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532680" target="_blank">link</a></td></tr>
              <tr><td>Benowo</td><td>SMK WACHID HASYIM 2 SURABAYA</td><td>JL. RAYA SEMEMI NO.7 SURABAYA                </td><td>031-7440568         </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20573861" target="_blank">link</a></td></tr>
              <tr><td>Bubutan</td><td>SMK NEGERI 7 SURABAYA</td><td>Jl. PAWIYATAN NO.2 SURABAYA                </td><td>(031)5342407        </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532197" target="_blank">link</a></td></tr>
              <tr><td>Bubutan</td><td>SMK BUBUTAN SURABAYA</td><td>Jl. BUBUTAN No.87 SURABAYA            </td><td> 5310432           </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532256" target="_blank">link</a></td></tr>
              <tr><td>Bubutan</td><td>SMK YPPI</td><td> Jl. Sulung 41-47 Surabaya        </td><td> 0313550388        </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=69829367" target="_blank">link</a></td></tr>
              <tr><td>Bulak</td><td>SMK TRI GUNA BHAKTI SURABAYA</td><td>Jl. KYAI TAMBAK DERES NO. 34 SURABAYA        </td><td> 031 51500309       </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532693" target="_blank">link</a></td></tr>
              <tr><td>Gayungan</td><td>SMKN 3 SURABAYA</td><td>Jl. AHMAD YANI SURABAYA                               </td><td>8412886             </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532195" target="_blank">link</a></td></tr>
              <tr><td>Gayungan</td><td>SMK DHARMA BHAKTI SURABAYA</td><td>     JL MENANGGAL I/32 GAYUNGAN SURABAYA                    </td><td> 0318281588         </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532173" target="_blank">link</a></td></tr>
              <tr><td>Genteng</td><td>SMKN 8 SURABAYA</td><td>Jl. KAMBOJA NO. 18 SURABAYA          </td><td>(031) 5342410       </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532198" target="_blank">link</a></td></tr>
              <tr><td>Genteng</td><td>SMK BERDIKARI - 2 SURABAYA</td><td>Jl. KAPASARI VI / 3 SURABAYA               </td><td>0313710028          </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532253" target="_blank">link</a></td></tr>
              <tr><td>Genteng</td><td>SMK FARMASI SURABAYA</td><td>JL. KAPASARI NO.3-5 SURABAYA       </td><td> 031 3710619      </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20552198" target="_blank">link</a></td></tr>
              <tr><td>Genteng</td><td>SMK KESEHATAN NUSANTARA</td><td>JL.SIMPANG DUKUH NO.11 SURABAYA   </td><td> 031-5458906  </td><td>S</td><td>-</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20570577" target="_blank">link</a></td></tr>
              <tr><td>Genteng</td><td>SMK RAJASA SURABAYA</td><td>JL. GENTENG KALI No.27 SURABAYA               </td><td>(031) 5344810       </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532681" target="_blank">link</a></td></tr>
              <tr><td>Genteng</td><td>SMK TRISILA SURABAYA</td><td>Jl. Undaan Kulon No. 57-59 Surabaya               </td><td> 031-5344364        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532706" target="_blank">link</a></td></tr>
              <tr><td>Gubeng</td><td>SMKN 5 SURABAYA</td><td>Jl. MAYJEND Prf Dr MOESTOPO 167-169 SURABAYA                 </td><td>0315934888          </td><td>N</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532211" target="_blank">link</a></td></tr>
              <tr><td>Gubeng</td><td>SMK 45 SURABAYA</td><td>Jl. JOJORAN I / 46  SURABAYA     </td><td>0315994020    </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532267" target="_blank">link</a></td></tr>
              <tr><td>Gubeng</td><td>SMK BERDIKARI - 1 SURABAYA</td><td>Jl. MAYJEN PROF.DR.MOESTOPO 79A  SURABAYA      </td><td> 031-5949157     </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532252" target="_blank">link</a></td></tr>
              <tr><td>Gubeng</td><td>SMK DR. SOETOMO SURABAYA</td><td>Jl. KARANG MENJANGAN - JOJORAN IV / 2 D  SURABAYA                           </td><td> 031-5914480        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532186" target="_blank">link</a></td></tr>
              <tr><td>Gubeng</td><td>SMK KESEHATAN BINA HUSADA SURABAYA</td><td>JL. KALIDAMI  NO. 14-16 SURABAYA           </td><td> 031-5993176        </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20571417" target="_blank">link</a></td></tr>
              <tr><td>Gubeng</td><td>SMK MAHARDHIKA SURABAYA</td><td>Jl. BARATA JAYA XII / 1  SURABAYA    </td><td> 0315014276   </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532206" target="_blank">link</a></td></tr>
              <tr><td>Gubeng</td><td>SMK METRIKA SURABAYA</td><td>Jl. PUCANG ADI 68  SURABAYA      </td><td> 5024680     </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532208" target="_blank">link</a></td></tr>
              <tr><td>Gubeng</td><td>SMK PARIWISATA SATYA WIDYA SURABAYA</td><td>Jl. MENUR NO. 2-A  SURABAYA   </td><td> 5030137  </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532200" target="_blank">link</a></td></tr>
              <tr><td>Gubeng</td><td>SMK YOS SUDARSO SURABAYA</td><td>Jl PUCANG ADI 130 A  SURABAYA       </td><td> 5944518      </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532697" target="_blank">link</a></td></tr>
              <tr><td>Gunung Anyar</td><td>SMK AL ISLAH SURABAYA</td><td>JL. RUNGKUT TENGAH NO. 31 SURABAYA</td><td>031-8781849    </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20541318" target="_blank">link</a></td></tr>
              <tr><td>Gunung Anyar</td><td>SMKS AL AMIN SURABAYA</td><td> Jln.Raya Rungkut Menanggal No.25 Surabaya </td><td> 031-8712637 </td><td>S</td><td>-</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20584024" target="_blank">link</a></td></tr>
              <tr><td>Jambangan</td><td>SMK KARTIKA 1 SURABAYA</td><td>Jl. KARAH NO. 182 SURABAYA                 </td><td>0318295118          </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532174" target="_blank">link</a></td></tr>
              <tr><td>Jambangan</td><td>SMK KARTIKA 2 SURABAYA</td><td>Jl. Karah No.182       </td><td>0318297958          </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532175" target="_blank">link</a></td></tr>
              <tr><td>Jambangan</td><td>SMK PGRI 3 SURABAYA</td><td>Jl. KARAH NO. 9  SURABAYA        </td><td> 8273850       </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532687" target="_blank">link</a></td></tr>
              <tr><td>Karangpilang</td><td>SMK MUHAMMADIYAH 2</td><td>JL. KEMLATEN BARU NO. 41-43 SURABAYA       </td><td> 7664181      </td><td>S</td><td>-</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20568497" target="_blank">link</a></td></tr>
              <tr><td>Karangpilang</td><td>SMK PGRI 14 SURABAYA</td><td>Jl. MASTRIP No. 45A  SURABAYA     </td><td> (031)7665104    </td><td>S</td><td>-</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532686" target="_blank">link</a></td></tr>
              <tr><td>Karangpilang</td><td>SMK SITI AMINAH</td><td> PERUM. GUNUNG SARI INDAH BLOK CC     </td><td> 031-7672304     </td><td>S</td><td>-</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=69812068" target="_blank">link</a></td></tr>
              <tr><td>Kenjeran</td><td>SMK PUTRA AIRLANGGA SURABAYA</td><td>Jl. POGOT BARU NO. 53  SURABAYA        </td><td> 031-3728820       </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532682" target="_blank">link</a></td></tr>
              <tr><td>Kenjeran</td><td>SMK WACHID HASYIM SURABAYA</td><td>Jl. SIDOTOPO WETAN BARU NO. 37  SURABAYA           </td><td>031-3764757  </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532711" target="_blank">link</a></td></tr>
              <tr><td>Krembangan</td><td>SMK IKIP SURABAYA</td><td>Jl. KAWUNG NO. 9  SURABAYA       </td><td> 0313535422      </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532191" target="_blank">link</a></td></tr>
              <tr><td>Krembangan</td><td>SMK KAL - 1 SURABAYA</td><td>KOBANGDIKAL  MOROKREMBANGAN SURABAYA          </td><td> 031-3281137        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532183" target="_blank">link</a></td></tr>
              <tr><td>Krembangan</td><td>SMK KAWUNG 1 SURABAYA</td><td>Jl. PARANG KLITIK NO. 2 SURABAYA      </td><td>031-3559146    </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532178" target="_blank">link</a></td></tr>
              <tr><td>Lakarsantri</td><td>SMK PGRI 7 SURABAYA</td><td>Jl .Raya Lidah Wetan No. 1 Surabaya    </td><td> 031-7521376       </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532689" target="_blank">link</a></td></tr>
              <tr><td>Lakarsantri</td><td>SMK WAHANA KARYA SURABAYA</td><td>Jl . KARANG PLOSO BAGKINGAN  SURABAYA      </td><td>  031 70522811    </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532712" target="_blank">link</a></td></tr>
              <tr><td>Mulyorejo</td><td>SMK GAMA CENDEKIA SURABAYA</td><td>JL.KALIJUDAN NO.34-B SURABAYA                  </td><td> 031-3810792        </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20571344" target="_blank">link</a></td></tr>
              <tr><td>Mulyorejo</td><td>SMK IPIEMS SURABAYA</td><td>JL. RAYA MENUR NO. 125 SURABAYA                  </td><td>031-5949790         </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20564057" target="_blank">link</a></td></tr>
              <tr><td>Mulyorejo</td><td>SMK PGRI 4 SURABAYA</td><td>Jl, KALIJUDAN IX 26-28                  </td><td> 031-70002241       </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20539250" target="_blank">link</a></td></tr>
              <tr><td>Pabean Cantian</td><td>SMK BARUNAWATI SURABAYA</td><td>JL. PERAK BARAT NO. 173                  </td><td> 3291312            </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20539249" target="_blank">link</a></td></tr>
              <tr><td>Pabean Cantian</td><td>SMK KAL - 2 SURABAYA</td><td>Jl. TELUK SAMPIT NO. 2 - B SURABAYA        </td><td>031-3283580       </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532182" target="_blank">link</a></td></tr>
              <tr><td>Pakal</td><td>SMK WIJAYA PUTRA SURABAYA</td><td>Jalan Raya Benowo No. 1-3, Surabaya                      </td><td>0317404404          </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532704" target="_blank">link</a></td></tr>
              <tr><td>Rungkut</td><td>SMK PERDANA 1 SURABAYA</td><td>Jl. KEDUNG ASEM NO. 80 SURABAYA            </td><td>8706264            </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532214" target="_blank">link</a></td></tr>
              <tr><td>Sambikerep</td><td>SMK GARUDA SURABAYA</td><td>Jl  MANUKAN WASONO GG. LEBAR NO.2 SURABAYA         </td><td>      031-7404604   </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532189" target="_blank">link</a></td></tr>
              <tr><td>Sambikerep</td><td>SMK PELAYARAN WIRA MARITIM SURABAYA</td><td>JL.RAYA KUWUKAN NO. 2 SURABAYA </td><td>   0317415569 </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532694" target="_blank">link</a></td></tr>
              <tr><td>Sambikerep</td><td>SMK TAMANSISWA SURABAYA</td><td>Jl. Lempung Mulya No. 1A           </td><td>031-7411838  </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20577829" target="_blank">link</a></td></tr>
              <tr><td>Sawahan</td><td>SMKN 4 SURABAYA</td><td>Jl. KRANGGAN NO. 81-101 SURABAYA                                     </td><td>0315345788          </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532196" target="_blank">link</a></td></tr>
              <tr><td>Sawahan</td><td>SMK NEGERI 2 SURABAYA</td><td>Jl. TENTARA GENIE PELAJAR ( PATUA ) NO. 26 SBY.                                </td><td>031-5343708         </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532203" target="_blank">link</a></td></tr>
              <tr><td>Sawahan</td><td>SMK ANTARTIKA SURABAYA</td><td>Jl. BANYU URIP KIDUL II/37 SURABAYA        </td><td>031-77652509 </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532257" target="_blank">link</a></td></tr>
              <tr><td>Sawahan</td><td>SMK BAHRUL ULUM</td><td>Jl. Putat Jaya Sekolahan No 70 - 72             </td><td>031- 5614691        </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20570572" target="_blank">link</a></td></tr>
              <tr><td>Sawahan</td><td>SMK GEMA 45 SURABAYA</td><td>Jl. MAYJEN SUNGKONO 106 SURABAYA            </td><td> 031-5661973        </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532190" target="_blank">link</a></td></tr>
              <tr><td>Sawahan</td><td>SMK GIKI 1 SURABAYA</td><td> Dukuh Kupang Utara I No.2           </td><td>5660828            </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20577334" target="_blank">link</a></td></tr>
              <tr><td>Sawahan</td><td>SMK KAWUNG 2 SURABAYA</td><td>Jl. Raya Simo Gunung No. 25 Surabaya.               </td><td> 031-5667680        </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532179" target="_blank">link</a></td></tr>
              <tr><td>Sawahan</td><td>SMK ST. LOUIS SURABAYA</td><td>Jl. TIDAR 117 SURABAYA           </td><td>  0315311277        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532677" target="_blank">link</a></td></tr>
              <tr><td>Sawahan</td><td>SMK TANWIR SURABAYA</td><td>Jl. Kedung Anyar VIII No.14-16 Surabaya                       </td><td> 031-5312445        </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20564065" target="_blank">link</a></td></tr>
              <tr><td>Semampir</td><td>SMK AL IRSYAD SURABAYA</td><td>JL. SULTAN ISKANDAR MUDA NO. 46       </td><td> (031) 3297220      </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20555432" target="_blank">link</a></td></tr>
              <tr><td>Semampir</td><td>SMK ARIF RAHMAN HAKIM SURABAYA</td><td> JL. TENGGUMUNG WETAN GANG 5/1     </td><td>     031 70305889 </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20577579" target="_blank">link</a></td></tr>
              <tr><td>Semampir</td><td>SMK Islam Al-Amal Surabaya</td><td>  Jl. Wonosari Lor 98 Surabaya     </td><td>  0313713482      </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20576251" target="_blank">link</a></td></tr>
              <tr><td>Semampir</td><td>SMK TEKNIK PAL SURABAYA</td><td>Jl. UJUNG SURABAYA                     </td><td> 031- 3286812       </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532692" target="_blank">link</a></td></tr>
              <tr><td>Simokerto</td><td>SMK ABI SURABAYA</td><td>Jl. Gembong No.48 Surabaya                </td><td>031-3718605         </td><td>S</td><td>C</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532259" target="_blank">link</a></td></tr>
              <tr><td>Simokerto</td><td>SMK MUHAMMADIYAH I SURABAYA</td><td>Jl .KAPASAN 73 - 75 SURABAYA                 </td><td> 031-3710559        </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532209" target="_blank">link</a></td></tr>
              <tr><td>Simokerto</td><td>SMK TRIYASA SURABAYA</td><td>Jl .KAPASARI PEDUKUHAN X/24 SURABAYA             </td><td>   3769335          </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532708" target="_blank">link</a></td></tr>
              <tr><td>Sukolilo</td><td>SMKN 10 SURABAYA</td><td>Jl. KEPUTIH TEGAL SURABAYA                    </td><td> 031 5939581        </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532204" target="_blank">link</a></td></tr>
              <tr><td>Sukolilo</td><td>SMK 17 AGUSTUS 1945 SURABAYA</td><td>Jl. NGINDEN SEMOLO 44 SURABAYA         </td><td> 5925238        </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532266" target="_blank">link</a></td></tr>
              <tr><td>Sukolilo</td><td>SMK ADHIKAWACANA SURABAYA</td><td>Jl. KEPUTIH III C PERUMAHAN NO. 1 SURABAYA       </td><td>5962140      </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532258" target="_blank">link</a></td></tr>
              <tr><td>Sukolilo</td><td>SMK KESEHATAN SURABAYA</td><td>JL. MEDOKAN SEMAMPIR INDAH NO. 27 SURABAYA           </td><td>031-5968122         </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20568499" target="_blank">link</a></td></tr>
              <tr><td>Sukolilo</td><td>SMK PRAPANCA 2 SURABAYA</td><td>Jl. NGINDEN INTAN TIMUR I/20 SURABAYA                      </td><td>5910718             </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532690" target="_blank">link</a></td></tr>
              <tr><td>Sukolilo</td><td>SMK PRAPANCA SURABAYA</td><td>Jl. NGINDEN INTAN TIMUR 1 SURABAYA                          </td><td>    5921789         </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532691" target="_blank">link</a></td></tr>
              <tr><td>Sukolilo</td><td>SMK UNITOMO SURABAYA</td><td> SEMOLOWARU No. 84    </td><td> 5991699 / 71601223 </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=60726708" target="_blank">link</a></td></tr>
              <tr><td>Sukolilo</td><td>SMK YESTA SURABAYA</td><td>Jl. Nginden II No. 135-137 Surabaya              </td><td> 5947528, 5931583   </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532696" target="_blank">link</a></td></tr>
              <tr><td>Sukomanunggal</td><td>SMK BHAKTI SAMUDERA</td><td>JL. SIMOHILIR RAYA 12         </td><td> 0317321415        </td><td>S</td><td> B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20552202" target="_blank">link</a></td></tr>
              <tr><td>Sukomanunggal</td><td>SMK KARTINI SURABAYA</td><td>JALAN SIMO GUNUNG BARAT TOL I/61-G SURABAYA  </td><td> 0317321986         </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532176" target="_blank">link</a></td></tr>
              <tr><td>Sukomanunggal</td><td>SMK KESEHATAN NUR MEDIKA</td><td>JL. SIMO POMAHAN I NO.4,8-10B SURABAYA             </td><td> 70505779           </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20574720" target="_blank">link</a></td></tr>
              <tr><td>Sukomanunggal</td><td>SMK PAWIYATAN SURABAYA</td><td>Jl. Tangkisturi no. 4-6 Surabaya     </td><td>  031-5342508 </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532202" target="_blank">link</a></td></tr>
              <tr><td>Sukomanunggal</td><td>SMK PGRI 10 SURABAYA</td><td>Jl. SIMO TAMBAAN SEKOLAHAN NO. 9 SURABAYA     </td><td> 7326419    </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532671" target="_blank">link</a></td></tr>
              <tr><td>Sukomanunggal</td><td>SMK SEJAHTERA SURABAYA</td><td>Jl. Simomulyo I/3            </td><td> 5476870            </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532674" target="_blank">link</a></td></tr>
              <tr><td>Sukomanunggal</td><td>SMK (STM) Siang Surabaya</td><td>JL. SIMO GUNUNG BARAT TOL I/61 SURABAYA     </td><td>  0317313771   </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20539247" target="_blank">link</a></td></tr>
              <tr><td>Tambaksari</td><td>SMK DIPONEGORO SURABAYA</td><td>Jl. KEDUNG SROKO V/15-21 SURABAYA          </td><td> 031-5023862        </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532185" target="_blank">link</a></td></tr>
              <tr><td>Tambaksari</td><td>SMK INDO BARUNA SURABAYA</td><td>JL. RANGKAH VI 55-57    </td><td>3712612    </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532192" target="_blank">link</a></td></tr>
              <tr><td>Tambaksari</td><td>SMK KATOLIK MATER AMABILIS SURABAYA</td><td>Jl. TERATAI 2-B SURABAYA     </td><td> 031-5034679    </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532177" target="_blank">link</a></td></tr>
              <tr><td>Tambaksari</td><td>SMK PGRI 6 SURABAYA</td><td>JL. KAPAS BARU XI/45 SURABAYA               </td><td> 031-3734074        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20539251" target="_blank">link</a></td></tr>
              <tr><td>Tambaksari</td><td>SMK TRI TUNGGAL SURABAYA</td><td>Jl. RANGKAH VI/55-59 SURABAYA                    </td><td>  (031) 3721455     </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532705" target="_blank">link</a></td></tr>
              <tr><td>Tandes</td><td>SMK DHARMA BAHARI</td><td>Jl. Sikatan Lebar XVI No. 1-5 Manukan Wetan SURABAYA     </td><td>7420948, 71891612   </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20541319" target="_blank">link</a></td></tr>
              <tr><td>Tandes</td><td>SMK PEMBANGUNAN</td><td>Jl. Balongsari Praja V/1       </td><td>    03177220211   </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20564064" target="_blank">link</a></td></tr>
              <tr><td>Tandes</td><td>SMK SARIPRAJA SURABAYA</td><td>Jl. LEMPUNG PERDANA NO.2 SURABAYA         </td><td> 031-7419719        </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532673" target="_blank">link</a></td></tr>
              <tr><td>Wonocolo</td><td>SMKN 12 SURABAYA</td><td>Jl. SIWALANKERTO PERMAI SURABAYA                  </td><td>(031)8436687        </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532210" target="_blank">link</a></td></tr>
              <tr><td>Wonocolo</td><td>SMK NEGERI 6 SURABAYA</td><td>Jl. MARGOREJO SURABAYA           </td><td>031 8438267         </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532212" target="_blank">link</a></td></tr>
              <tr><td>Wonocolo</td><td>SMK KRISTEN PETRA SURABAYA</td><td>Jl. JEMUR ANDAYANI XVI/16-18  SURABAYA                </td><td>(031) 8417391       </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532194" target="_blank">link</a></td></tr>
              <tr><td>Wonocolo</td><td>SMK PGRI 13 SURABAYA</td><td>Jl. SIDOSERMO PDK  IVE/2 SURABAYA            </td><td>031-8471604         </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532685" target="_blank">link</a></td></tr>
              <tr><td>Wonocolo</td><td>SMK PGRI 1 SURABAYA</td><td>Jl. Jemursari VIII No.120 Surabaya        </td><td> 031-8473730        </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532452" target="_blank">link</a></td></tr>
              <tr><td>Wonokromo</td><td>SMKN 1 SURABAYA</td><td>  Jl. SMEA No. 4 Surabaya         </td><td>  031-8292038       </td><td>N</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532205" target="_blank">link</a></td></tr>
              <tr><td>Wonokromo</td><td>SMK BRAWIJAYA SURABAYA</td><td>Jl. BRATANG WETAN III-A/2 - 6  SURABAYA     </td><td>   5044561  </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532255" target="_blank">link</a></td></tr>
              <tr><td>Wonokromo</td><td>SMK FARMASI SEKESAL SURABAYA</td><td>JL. GADUNG NO. 2 SURABAYA             </td><td>031-8404202         </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20549500" target="_blank">link</a></td></tr>
              <tr><td>Wonokromo</td><td>SMK GANESYA 2 SURABAYA</td><td>Jl. Menur II/68  SURABAYA      </td><td>0317071224</td><td>S</td><td>C</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532188" target="_blank">link</a></td></tr>
              <tr><td>Wonokromo</td><td>SMK KESEHATAN TERPADU SURABAYA</td><td>Jl. Raya Ngagel No.89   </td><td>  031 5022217     </td><td>S</td><td></td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=90000033" target="_blank">link</a></td></tr>
              <tr><td>Wonokromo</td><td>SMK KETINTANG SURABAYA</td><td>Jl. KETINTANG 147 SURABAYA                             </td><td>031-8284121         </td><td>S</td><td>A</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532180" target="_blank">link</a></td></tr>
              <tr><td>Wonokromo</td><td>SMK PGRI 5 SURABAYA</td><td>JL. KARANG REJO  4/16              </td><td>031- 8295241     </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532688" target="_blank">link</a></td></tr>
              <tr><td>Wonokromo</td><td>SMK PURUHITA SURABAYA</td><td>JL JAGIR WONOKROMO NO 112         </td><td> 031-8496094        </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20554119" target="_blank">link</a></td></tr>
              <tr><td>Wonokromo</td><td>SMK TUNAS WIJAYA SURABAYA</td><td>Jl. DARMO REJO III/54-56  SURABAYA       </td><td> 5665745      </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532710" target="_blank">link</a></td></tr>
              <tr><td>Wonokromo</td><td>SMK WIJAYA SURABAYA</td><td>Jl .GADUNG III.No. 5 SURABAYA    </td><td> 031.8470694   </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532702" target="_blank">link</a></td></tr>
              <tr><td>Wonokromo</td><td>SMK WONOKROMO SURABAYA</td><td>Jl. PULO WONOKROMO NO 241  SURABAYA             </td><td>   031-8284084      </td><td>S</td><td>B</td><td><a href="http://profilsekolah.dispendik.surabaya.go.id/umum/sekolah.php?id=20532695" target="_blank">link</a></td></tr>

          </tbody>
      </table>
  </div>
</div>


       


